name: "sft_v1"
args: 
  # Main arguments
  learning_rate: 0.0001
  num_train_epochs: 3
  lr_scheduler_type: "cosine"
  
  # Efficient training
  fp16: True
  gradient_checkpointing: True 
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8 

  # Other less important 
  warmup_ratio: 0.1 

seed: 32
